import {
  SiAnsible,
  SiApachekafka,
  SiCisco,
  SiCloudnativebuild,
  SiDocker,
  SiGithubcopilot,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiOpenjdk,
  SiServerless,
  SiSpring,
  SiStackshare,
  SiVagrant,
} from 'react-icons/si';

export const technologyIcons = {
  ansible: { Icon: SiAnsible, label: 'Ansible' },
  aws: { Icon: SiServerless, label: 'Amazon Web Services' },
  cisco: { Icon: SiCisco, label: 'Cisco' },
  copilot: { Icon: SiGithubcopilot, label: 'GitHub Copilot' },
  docker: { Icon: SiDocker, label: 'Docker' },
  heroku: { Icon: SiCloudnativebuild, label: 'Heroku' },
  java: { Icon: SiOpenjdk, label: 'Java' },
  kafka: { Icon: SiApachekafka, label: 'Apache Kafka' },
  lambda: { Icon: SiServerless, label: 'AWS Lambda' },
  mongo: { Icon: SiMongodb, label: 'MongoDB' },
  mysql: { Icon: SiMysql, label: 'MySQL' },
  node: { Icon: SiNodedotjs, label: 'Node.js' },
  oracle: { Icon: SiStackshare, label: 'Oracle SQL & GoldenGate' },
  spring: { Icon: SiSpring, label: 'Spring' },
  vagrant: { Icon: SiVagrant, label: 'Vagrant' },
};
